'use strict';

module.exports = {
  version: '2026.09.14',
  features: {
    continuum_paths: true,
    date_range: true,
    date_range_mode: 'recent_lookback_filter',
    pagination: true,
    lite_fetch: true,
    max_limit: 50000,
    cleanup_delete_max: 10000,
    daily_cleanup: true,
    daily_cleanup_default_limit: 5000,
    daily_cleanup_default_lookback: '30d',
    daily_cleanup_progress: true,
    never_trash_senders: true,
    move_to_folder: true,
    copy_folder_to_inbox: true,
    folder_persona_ingest: true,
    attitude_timeline: true,
    email_quote_search: true,
    web_search: true,
    sender_rule_trash: true,
    background_email_jobs: true,
    year_cleanup: true,
    year_cleanup_checkpoint: true,
    year_cleanup_weekly_slices: true,
    email_job_cancel: true,
    email_job_progress_log: true,
    email_cleanup_preview: true,
    memory_cleanup: true,
    memory_cleanup_cron: true,
    cleanup_folder_rules: true,
  },
};
